# @package extensions.balancer

_target_: airflow_balancer.BalancerConfiguration
default_username: timkpaine
default_key_file: /home/airflow/.ssh/id_rsa
primary_queue: primary
secondary_queue: workers
hosts:
  - name: nuc2
    os: ubuntu
    size: 32
    queues: [primary]
    tags: []

ports:
  - host_name: nuc2
    port: 22
    tags: []

  - name: named-port
    host: ${...hosts[0]}
    # no dupe
    port: 23
    tags: []

  - name: test-supervisor-port
    host_name: nuc2
    port: 9091
    tags: [supervisor]
