# Changes here will be overwritten by Copier
_commit: c53b04c
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: DAGs to validate airflow-laminar packages
project_name: validation-dags
python_version_primary: '3.11'
team: the airflow-laminar authors
