# @package extensions.libraries

defaults: []
_target_: airflow_common.LibraryList
git:
  - name: airflow-balancer
    repo: git@github.com:airflow-laminar/airflow-balancer.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-common
    repo: git@github.com:airflow-laminar/airflow-common.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-config
    repo: git@github.com:airflow-laminar/airflow-config.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-ha
    repo: git@github.com:airflow-laminar/airflow-ha.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-priority
    repo: git@github.com:airflow-laminar/airflow-priority.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-pydantic
    repo: git@github.com:airflow-laminar/airflow-pydantic.git
    branch: main
    dir: /mnt/home/airflow/
  - name: airflow-supervisor
    repo: git@github.com:airflow-laminar/airflow-supervisor.git
    branch: main
    dir: /mnt/home/airflow/
  - name: supervisor-pydantic
    repo: git@github.com:airflow-laminar/supervisor-pydantic.git
    branch: main
    dir: /mnt/home/airflow/
